In [ ]:
import pandas as pd
df = pd.read_csv('live_shipments.csv')
df.drop(columns=['event_type'], inplace=True)
df.to_csv('live_shipments.csv', index=False)

,shipment_id,carrier,weather,shipment_value,warehouse_load_pct,traffic_density,planned_arrival,current_delay_minutes,is_delayed,last_checkpoint,distance_to_go_km,shipment_priority
0,oB-56947942,Swift,Clear,1809,87,0.98,2026-03-09 06:29:47.054008,99,1,East Amandashire Hub,22,High
1,Pb-89346154,BlueDart,Clear,600,49,0.45,2026-03-09 00:29:47.054008,9,0,South Daniel Hub,327,Medium
2,nl-11821062,Swift,Clear,11453,85,0.20,2026-03-08 01:29:47.055031,60,1,Lake Roy Hub,385,High
3,ko-27943858,Swift,Fog,12340,64,0.22,2026-03-08 23:29:47.055031,14,0,Coxtown Hub,14,Medium
4,dx-31203927,Delhivery,Clear,11562,52,0.75,2026-03-09 10:29:47.055031,15,0,North Jack Hub,450,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...
95,LX-35598247,Swift,Clear,3715,31,0.68,2026-03-08 18:29:47.070721,9,0,Martinchester Hub,49,High
96,UX-33889425,Swift,Clear,13433,83,0.74,2026-03-09 12:29:47.070721,2,0,Port Carrieton Hub,129,Medium
97,NB-09442653,BlueDart,Clear,5367,68,0.52,2026-03-09 18:29:47.070721,2,0,New Alice Hub,91,Medium
98,NG-22109572,Delhivery,Fog,12538,95,0.35,2026-03-08 01:29:47.070721,140,1,Port Katrina Hub,449,Low
99,lI-97481840,BlueDart,Clear,8942,34,0.62,2026-03-09 12:29:47.070721,12,0,South Robert Hub,94,Low

In [ ]:
df2 = pd.read_csv('historical_logistics.csv')
df2.drop(columns=['event_type'], inplace=True)
df2.to_csv('historical_logistics2.csv', index=False)

,shipment_id,carrier,weather,shipment_value,warehouse_load_pct,traffic_density,planned_arrival,current_delay_minutes,is_delayed,last_checkpoint,distance_to_go_km,shipment_priority
0,FJ-82823588,Delhivery,Heavy Rain,10753,91,0.25,2026-02-16 17:31:39,163,1,East Austin Hub,468,High
1,kq-40251081,Delhivery,Clear,5202,78,0.51,2026-02-10 19:41:46,7,0,Tamaraburgh Hub,54,Low
2,YH-75059296,Swift,Fog,7599,100,0.46,2026-02-15 02:32:54,4,0,Martinbury Hub,358,Low
3,Wh-78892433,BlueDart,Fog,12401,30,0.95,2026-03-08 18:29:49,12,0,East Maryborough Hub,150,Low
4,km-65944917,BlueDart,Fog,13820,73,0.62,2026-02-24 17:03:22,2,0,Lake Eddiemouth Hub,252,High
...,...,...,...,...,...,...,...,...,...,...,...,...
995,zT-77844970,Delhivery,Heavy Rain,5176,43,0.20,2026-02-27 15:15:39,7,0,Jessicashire Hub,218,Low
996,Wb-54841561,Swift,Cyclone,1591,62,0.65,2026-02-09 06:00:06,555,1,West Charlesfurt Hub,134,High
997,GI-34423263,BlueDart,Clear,9382,67,0.13,2026-02-09 22:57:22,0,0,Port Jeanne Hub,489,High
998,at-81911581,Delhivery,Heavy Rain,5328,95,0.70,2026-02-22 05:54:58,13,0,Port Joshua Hub,361,Medium
999,JK-43799249,Swift,Heavy Rain,12994,81,0.37,2026-03-04 04:58:05,4,0,Smithland Hub,25,Medium